services:
  editorfrontend:
    build: .
    container_name: "editor_frontend"
    restart: unless-stopped
    networks:
      - fdd-docker
    ports:
      - 8082:3000

networks:
  fdd-docker:
    external: true