services:
  editor_watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  editorfrontend:
    image: ghcr.io/firstdarkdev/fdd-editor:latest
    container_name: "editor_frontend"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - fdd-docker
    ports:
      - 8082:3000

networks:
  fdd-docker:
    external: true