name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/fdd-editor:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/fdd-editor:${{ github.sha }}

      - name: Tag Docker image with version
        if: startsWith(github.ref, 'refs/tags')
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/fdd-editor:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/fdd-editor:${{ github.ref_name }}
          docker push ghcr.io/${{ github.repository_owner }}/fdd-editor:${{ github.ref_name }}

      - name: Tag Docker image as latest
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/fdd-editor:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/fdd-editor:latest
          docker push ghcr.io/${{ github.repository_owner }}/fdd-editor:latest